version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    - npm prune --production
  build:
    commands:
      - npm run build
artifacts:
  base-directory: dist
  files:
    - "**"
    - node_modules/**
  discard-paths: no
