AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  createPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/posts/create.handler
      Runtime: nodejs20.x
      CodeUri: .
#      Layers:
#        - !Ref InfraMysqlLayer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /posts
            Method: POST
      Environment:
        Variables:
          NODE_ENV: "dev"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        External:
          - pg-hstore
          - pg
        EntryPoints:
          - src/handlers/posts/create.ts
#  InfraMysqlLayer:
#    Type: AWS::Serverless::LayerVersion
#    Properties:
#      ContentUri: ./infra-mysql.zip
#      CompatibleRuntimes:
#        - nodejs20.x