AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  createPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/posts/create.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 100
      CodeUri: .
      Events:
        Api:
          Type: Api
          Properties:
            Path: /posts
            Method: POST
#      Environment:
#        Variables:
#          NODE_ENV: "production"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        External:
          - aws-sdk
          - pg-hstore
          - pg
        EntryPoints:
          - src/handlers/posts/create.ts