AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs20.x
      ContentUri: ./deps.zip
      Description: Dependencies for Lambda functions

  createPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/posts/create.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 100
      Layers:
        - !Ref DependenciesLayer
      CodeUri: .
      Events:
        Api:
          Type: Api
          Properties:
            Path: /posts
            Method: POST
      Environment:
        Variables:
          NODE_ENV: "production"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        External:
          - aws-sdk
          - pg-hstore
          - pg
          - mysql2
          - sequelize
          - "@aws-sdk/client-secrets-manager"
        EntryPoints:
          - src/handlers/posts/create.ts
